### ISSUE TITLE
[CoE Starter Kit - BUG] number of portals are not match in COE

### ISSUE THREAD

**Issue by Raz-786** [microsoft/coe-starter-kit#10206]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Portal Syn flow failed
<img width="1124" height="752" alt="Image" src="https://github.com/user-attachments/assets/3b522faf-864a-4d9a-a76b-8a66f31444b1" />

ActionConditionFailed
The execution of template action 'List_Envt_Portals' is skipped: the 'runAfter' condition for action 'List_Portals'

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.49.2

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Portals)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by mohamrizwa** [comment]
Hi @Raz-786,
This issue has been fixed in latest release.
Please proceed with upgrading to the latest version of the Center of Excellence (CoE) Starter Kit. Before starting, ensure all unmanaged layers are identified and removed to avoid deployment issues. 
For detailed guidance, refer to the below -mentioned 
 official documentation: 
 https://learn.microsoft.com/power-platform/guidance/coe/after-setup 

Feel free to reach out if you need any assistance. We're happy to help!

**Comment by Raz-786** [comment]
<img width="1879" height="675" alt="Image" src="https://github.com/user-attachments/assets/4f0dad63-bf0e-490d-8bc8-ce776b0939af" />

Hi 
I upgrade core solution to 4.50.x and getting an error, also in 2nd screenshot who Rajeev user getting alert?

<img width="1593" height="105" alt="Image" src="https://github.com/user-attachments/assets/37073075-9a50-483a-9c50-76c34865676c" />

**Comment by mohamrizwa** [comment]
Hi @Raz-786,

Please verify the below steps:
 
Recheck Unmanaged Layers
Use the https://learn.microsoft.com/power-platform/guidance/coe/after-setup to ensure all unmanaged layers are removed before redeploying.

Manually Validate Flow Dependencies
Open the flow in Power Automate and inspect the runAfter conditions. Ensure List_Portals is not failing due to missing permissions or misconfigured connectors.


Review Flow Run History
Use Power Automate’s run history and enable additional columns to debug the exact failure point. Refer to [Microsoft’s troubleshooting guide](https://learn.microsoft.com/en-us/power-automate/fix-flow-failures). [[Troublesho...soft Learn]](https://learn.microsoft.com/en-us/power-automate/fix-flow-failures)


Check Azure DevOps Sync Logs
If your flow interacts with Azure DevOps, review the [Azure AD Connect logs](https://www.coreview.com/blog/azure-ad-connect-logs-how-to-troubleshoot-sync-issues-in-azure-ad) for deeper diagnostics.

**Comment by Raz-786** [comment]
Hello 

This time i was able to upgrade to 4.5 but Flow still not pulling Portals information 
I update this and published 

<img width="1278" height="63" alt="Image" src="https://github.com/user-attachments/assets/00b90d0c-4a15-40f7-8596-45aa9361d296" />

<img width="1309" height="759" alt="Image" src="https://github.com/user-attachments/assets/499490a7-ba57-4f7e-810c-f642f648fb19" />

**Comment by mohamrizwa** [comment]
Hi @Raz-786, 
Unable to see the any error in above screen shot. I would request you run that flow manually and proceed to debug the issue and identify the root cause. If any errors are encountered during the debug. Additionally, share the error details along with relevant screenshots to support further analysis and resolution.

**Comment by mohamrizwa** [comment]
We haven’t heard back in a while, so we’ll proceed to close this issue for now. If the issue persists or you need further assistance, feel free to a new issue. We’re happy to help anytime. Thanks again for your engagement!

**Comment by Raz-786** [comment]
Problem is instruction is not clear and there is no way to get you involve via Screen sharing, so please don't close this incident, I spoke MS engineer just waiting for her meeting invite

Thanks

**Comment by mohamrizwa** [comment]
We haven’t heard back in a while, so we’ll proceed to close this issue for now. If the issue persists or you need further assistance, feel free to a new issue. We’re happy to help anytime. Thanks again for your engagement!

**Comment by mohamrizwa** [comment]
We haven’t heard back in a while, so we’ll proceed to close this issue for now. If the issue persists or you need further assistance, feel free to a new issue. We’re happy to help anytime. Thanks again for your engagement!
