### ISSUE TITLE
[CoE Starter Kit - BUG] 'The API operation 'Get-Connectors' requires the 'property' to be of type 'String' but is of type 'Boolean'.'

### ISSUE THREAD

**Issue by alexserdan3246** [microsoft/coe-starter-kit#10248]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Multiple Cloud Flows throw the following error:

The API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/207/properties/connectionParameters/password/uiDefinition/constraints/required' to be of type 'String' but is of type 'Boolean'.'

We have disabled the inventory flag for some environments and even then,

<img width="1894" height="866" alt="Image" src="https://github.com/user-attachments/assets/b1b5d3f6-936a-40eb-9154-ec3dd07f046d" />

 we have the error. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.50.4 (September Release)

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Custom Connectors)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by mibejamsft** [comment]
Was checking this and it seems to be Region specific, not related to CoE kit.

**Comment by mohamrizwa** [comment]
Hi @alexserdan3246,
I would request you to verify the below steps:
**1. Region-Specific Workaround**
            As noted by GitHub member mibejamsft, the issue appears to be region-specific. If possible, test the flow in a different region    or environment to confirm whether the error persists. 
**2. Manual Schema Correction**
If you have access to the connector definition:
         1. Navigate to the Custom Connector schema.
         2. Locate the connectionParameters > password > uiDefinition > constraints > required field.
         3. Ensure its value is explicitly set as a String ("true" or "false"), not a Boolean (true or false).
**3. Use Test Flow for Isolation**
As suggested in related threads, build a test flow using the Get Custom Connectors as Admin action to isolate the error. This helps confirm whether the issue is tied to permissions or schema inconsistencies. 
**4. Check Permissions**
Ensure that the System Admin SR role includes the ManageAnyCustomApi permission. While some environments work without it, others may require it for successful execution.

**Comment by mibejamsft** [comment]
This seems to be happening because the Get Connectors is returning all existing connectors, but if 1 of the connectors as a wrong configuration, it will fail.
It is being handled by that connector developer to deploy the fix.

**Comment by abir-mouaouya** [comment]
@mibejamsft

For my part, I also checked and it’s a problem related to the region. Could you please explain more why the problem is region‑related? What is the difference? In my case, I have the problem for the France region but not for Europe.

**Comment by mibejamsft** [comment]
The problem is related to a connector that exists only in some regions and not in others, don't know if is because it wasn't made available on other regions.
What is happening is that connector (3rd party) is with a wrong configuration and when you try to pull all the list of available connectors, that one is breaking the Power Apps for Makers connector to retrieve the list.
We already talked with the IP of that connector, and he made the changes, it is a matter of waiting for the fix to be released in those regions.
Will provide update about this soon.

**Comment by mohamrizwa** [comment]
Hi @alexserdan3246,
I would request you raise a MS ticket for this. Meanwhile we are trying to find workaround for this.

**Comment by alexserdan3246** [comment]
> Hi [@alexserdan3246](https://github.com/alexserdan3246), I would request you raise a MS ticket for this. Meanwhile we are trying to find workaround for this.

Great news from CSS: 

_I hope this message finds you well. I’m writing to follow up on my previous email concerning your case 2509231420001111. As I mentioned earlier, the issue you're experiencing falls outside the scope of our Power Automate break-fix support team. We previously provided you with the COE team link, as they have the expertise to assist you in a better way.

Could you please let me know if you had a chance to reach out to them or if you need any further assistance from our side? We are here to help you and ensure your concerns are addressed._

**Comment by mibejamsft** [comment]
Hi @alexserdan3246, you open it regarding the CoE Kit...but the problem is in the Connector "Power Apps for Makers" like I mentioned before, not in the CoE kit itself, which this github project is where all the CoE problems should be addressed, so it is not surprising that they answered that.

If you just had mentioned the problem in the connector + error message, maybe you wouldn't have received that reply.

Only after that reply that you referenced this thread when you could have done it in the problem description also...it would've avoided that.

Anyway, regarding the problem of the Connector, the fix is ready to be released, it is just a matter of waiting for it, I still don't have any ETA.

**Comment by venkata-vijay** [comment]
Hi Team,
We are facing the issue as well, but for us the issue is specific for the environments in the 'South America' region.
All the other environments are working fine.

**Comment by hygornet** [comment]
Hi team,

I’ve just completed an installation in an environment with the United States and South America region, and the same error occurred for me.
Are we indeed waiting for a fix for this issue?

Thank you.

**Comment by mibejamsft** [comment]
@hygornet 
Yes, there was some internal problems that now were overcome and waiting for validation to be deployed.
I still don't know if it will be all at once for all regions or it will have batch releases.

**Comment by hygornet** [comment]
> [@hygornet](https://github.com/hygornet) Yes, there was some internal problems that now were overcome and waiting for validation to be deployed. I still don't know if it will be all at once for all regions or it will have batch releases.

Hi @mibejamsft ,

thanks for your response.
Ok, i will wait for the new version of the solution.
Thanks!

**Comment by mibejamsft** [comment]
It isn't a new version of the solution, it is a Connector that I think it is used there, once that gets updated, it should start to work fine.

**Comment by hygornet** [comment]
> It isn't a new version of the solution, it is a Connector that I think it is used there, once that gets updated, it should start to work fine.

In fact, the error occurs when listing the Connector. I installed the CoE in a trial environment (Azure region West US) and everything worked fine, but when I install it in another tenant in the Brazil South region, this connector in flow fails.

**Comment by mohamrizwa** [comment]
Hi @hygornet,
I raised a ticket with Microsoft and connected with their team. They confirmed that this is a known issue and they are currently working on resolving it.

**Comment by SkippingAdi** [comment]
Hi all

I still don't understand the origin of that error. 
We have the error as well (region: switzerland). 
I created a complete new Environment in region switzerland with no Dataverse Database, created a new flow with only the Power App for Makers Connector and the Get Connectors Action and the flow fails with the same error. It is equally strange that when I create a new environment with Dataverse Database in the Switzerland region, the same error occurs even though there are no connectors in the new environment yet.
So in my understanding it is not a problem of "a custom connector" but a problem of the Power App for Makers connector, right?

**Comment by mibejamsft** [comment]
@SkippingAdi 
As I explained before, the Power Apps for Makers connector retrieves all the existing connectors and since there is 1 3rd party custom connector that isn't right, it breaks the Power Apps for Makers.
The deploy of the fix should be soon.

**Comment by SkippingAdi** [comment]
Hi @mibejamsft 

Thank you for the clarification. 

Until now, due to poor documentation of this Get Connectors action, I understood that it loads all connectors from the environment specified in the filter. However, this is obviously not the case. I have found an environment (Europe) where Get Connectors works. Get Connectors actually loads all connectors from wherever they are and not just those from the environment specified in the filter. Can someone explain to me why the filter condition is necessary? It must apparently contain a valid Environment ID from the tenant. But why?

**Comment by mibejamsft** [comment]
@SkippingAdi 
It seems the custom connector didn't reach Europe yet, so that is why it is working.
The filter is for environment and retrieves all that exist for that environment.

**Comment by Sreenivasulu1999** [comment]
Cloud you please let me know when this is fixed from Microsoft team

**Comment by mibejamsft** [comment]
Hello all,

It seems the issue is now fixed, I've tested one flow with the connector a now runs fine.

**Comment by mohamrizwa** [comment]
Hi @mibejamsft,
Yes, I observed that issue is fixed now. I would request you to close this ticket.

**Comment by mibejamsft** [comment]
I don't have permission to close it.
@alexserdan3246  I think you can do it.

**Comment by mohamrizwa** [comment]
Hi @alexserdan3246,
Thanks for your support. I am closing this ticket.

**Comment by ElderScroll1** [comment]
Hello @mibejamsft 
I had the same problem with the contents of this ticket today(10/16). Has this problem not been solved yet?

**Comment by SuffolkPowerApps** [comment]
I've just installed the CoE starter kit in the UK and am getting this issue too

**Comment by mibejamsft** [comment]
We are seeing again the issue happening in some regions, not all and intermittently, but I don't know yet where is coming from.
I'm discussing this with the Product Group to know what is...will give updates.

**Comment by pleasedeleteme1234343** [comment]
also getting this issue

**Comment by SkippingAdi** [comment]
Good morning
For us (located in switzerland) the get-connectors flow seems to work for most regions. Only europe region still fails with the same error. Perhaps this region has not yet been updated?

**Comment by mibejamsft** [comment]
Right now we just know that Australia isn't working as expected, but I tested on France for example and is working fine, crm4 (Europe) is also working fine.

**Comment by mibejamsft** [comment]
I've got confirmation that the fix should be deployed for all regions, the issue shouldn't be happening anymore
