### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Connectors) - Failed

### ISSUE THREAD

**Issue by Fabien-M** [microsoft/coe-starter-kit#10279]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

I just installed the Sep'25 CoE revision as an update, when launching the App 'CoE Setup and Upgrade Wizard', on the 'Run Setup flows' the flow 'Admin | Sync Template v3 (Connectors)' is not up and running, after trying to launch the flow manually I had a error 
"The action « Get_Connectors » failed: The API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/210/properties/connectionParameters/password/uiDefinition/constraints/required' to be of type 'String' but is of type 'Boolean'.'

### Expected Behavior

The flow 'Admin | Sync Template v3 (Connectors)' must run without any issue

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.50.4

### What app or flow are you having the issue with?

'Admin | Sync Template v3 (Connectors)'

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

In my CoE env, just try to run the flow ''Admin | Sync Template v3 (Connectors)''

**Comment by mohamrizwa** [comment]
Hi @Fabien-M,
The issue appears to be related to a connector that is available only in certain regions. Could you please verify which region the environment is associated with where this error is occurring.

**Comment by Fabien-M** [comment]
Hello @mohamrizwa , My current region is France and it seems the connector is available

**Comment by bdestrada** [comment]
Hi,

After installing version 4.50.4, we are facing the same issue. Our environments are in South America. Is there any way to fix the problem?

**Comment by mohamrizwa** [comment]
Hi @bdestrada,
I raised a ticket with MS product team. They confirmed that this is a known issue and they are currently working on resolving it.

**Comment by mohamrizwa** [comment]
Hi @Fabien-M,
This issue is resolved; I would request you to please verify.

**Comment by Fabien-M** [comment]
Hello @mohamrizwa , seems better from my side, thank you.

**Comment by bvoller-tec** [comment]
I am seeing the same issue on 'Admin | Sync Template v3 (Connectors)' after upgrading from 4.50.2 to 4.50.4 today.

Action 'Get_Connectors' failed: The API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/209/properties/connectionParameters/password/uiDefinition/constraints/required' to be of type 'String' but is of type 'Boolean'.'

Flow ran successfully prior to upgrade, now fails every time when manually run.

Region: Australia

**Comment by ndkits-a-hirose** [comment]
Upgrading from 4.50.2 to 4.50.4 today.

I encountered an error in version 4.50.2,
and the same error still occurs after updating to 4.50.4.

Here is the error message:

`Action 'Get_Connectors' failed: The API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/210/properties/connectionParameters/password/uiDefinition/constraints/required' to be of type 'String' but is of type 'Boolean'.'
`
My region: Japan

**Comment by mohamrizwa** [comment]
Hi @ndkits-a-hirose,
I would request to share the below details for raising this to MS product team:
1. Environment URL
2. Environment ID
3. Region
4. Error Screenshot

**Comment by jackpoz** [comment]
The same error started today for me too
"Action 'Get_Connectors' failed: The API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/209/properties/connectionParameters/password/uiDefinition/constraints/required' to be of type 'String' but is of type 'Boolean'.'"

I don't know if the flow is scheduled daily or weekly, but today I received the "Admin | Sync Flow Errors" email with the flow failing on all environments.

<img width="1523" height="104" alt="Image" src="https://github.com/user-attachments/assets/10c53ab3-6d61-44e3-b373-dd70241c315e" />

Region: Europe
Environment ID: c93611fd-8579-4f99-9e47-f77626e61a5b (but all the environments in my tenant errored out)

**Comment by MaKraMc** [comment]
I have the same error since today as well

**Comment by ndkits-a-hirose** [comment]
@mohamrizwa 
Region: Japan
<img width="1503" height="850" alt="Image" src="https://github.com/user-attachments/assets/dd3cd201-e9df-47b5-9c23-4f4908c9a175" />

We regret to inform you that we cannot share the ID in a public forum.

**Comment by DaisyZ6166** [comment]
We have the same error message from this flow Admin | Sync Template v3 (Connectors) since Oct. 14th.
Region: Australia.

**Comment by DaisyZ6166** [comment]
> Hi [@bdestrada](https://github.com/bdestrada), I raised a ticket with MS product team. They confirmed that this is a known issue and they are currently working on resolving it.

Hi, just wondering do you have any update on this yet?
Thanks

**Comment by bvoller-tec** [comment]
> I am seeing the same issue on 'Admin | Sync Template v3 (Connectors)' after upgrading from 4.50.2 to 4.50.4 today.
> 
> Action 'Get_Connectors' failed: The API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/209/properties/connectionParameters/password/uiDefinition/constraints/required' to be of type 'String' but is of type 'Boolean'.'
> 
> Flow ran successfully prior to upgrade, now fails every time when manually run.
> 
> Region: Australia

My issue has cleared and flow **Admin | Sync Template v3 (Connectors)** has run successfully multiple times when manually triggered.

**Comment by davidkumarit-debug** [comment]
We have same issue from this flow. Any update on this?

Location: Singapore

**Comment by mohamrizwa** [comment]
As analyzed, we’ve confirmed this issue is related to the PowerApps product feature “Get Connectors.” We are already coordinating with the product team, and they have indicated that the resolution is expected by the end of this month.
To help them better understand the situation, please provide the following details:

Organization URL
Environment ID
Region
Screenshot of the error

**Comment by mohamrizwa** [comment]
Hi @Fabien-M,
This issue is resolved, please verify and update accordingly.

**Comment by ndkits-a-hirose** [comment]
The issue has been resolved. Thank you.
