### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (Custom Connectors) flow failed 90% of execution

### ISSUE THREAD

**Issue by vynarim** [microsoft/coe-starter-kit#10309]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hello

Since 5th of september 2025 almost 90% of this flow executions are failing
As exemple, on 03/10/2025, for 80 executions, 72 failed, 8 succeeded
Before 05/09/2025 every run succeeded

I deployed the september release on 22/09/2025 and before I was on the august version of Coe Starter Kit

Error message is always the same

L'action « Get_Connectors » a échoué: The API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/212/properties/connectionParameters/password/uiDefinition/constraints/required' to be of type 'String' but is of type 'Boolean'.'

<img width="1666" height="1247" alt="Image" src="https://github.com/user-attachments/assets/d55f3f7f-4eab-4ae0-964f-3db151d05718" />

<img width="1662" height="1262" alt="Image" src="https://github.com/user-attachments/assets/1759d7fa-cec5-4ced-bc31-ed2a23e0c007" />

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents_4_50_4_managed

### What app or flow are you having the issue with?

Sync Template v4 (Custom Connectors)

### What method are you using to get inventory and telemetry?

None

**Comment by AmarSaiRam** [comment]
Hi, @vynarim 
1. Review Connector Definition
Open the Custom Connector used in the "Sync Template v4 (Custom Connectors)" flow.
Navigate to the definition for the "Get_Connectors" operation.
Inspect the schema for the returned object, specifically:
body/value/.../connectionParameters/password/uiDefinition/constraints/required
Ensure that the required property is properly typed as a string if the flow expects a string, or update the flow logic to accept a boolean if that's now the correct schema.
2. Update the Flow Logic
If the API now returns a boolean, update the flow so it handles both boolean and string values.
You might need to add a conversion step in the flow (e.g., use Power Automate's expression language to convert boolean to string if necessary).
3. Check Release Notes & Documentation
Review the release notes of both the CoE Starter Kit and Power Platform API for any schema changes related to custom connectors or the required property.
If this is a breaking change introduced by Microsoft, update your implementation accordingly.
4. Rollback or Hotfix
If an immediate fix is needed and the September release is incompatible, consider rolling back to the August version until a proper fix is applied.
Alternatively, apply a hotfix to the flow or connector definition.
5. Contact Microsoft Support
If this behavior is unintended, raise the issue with Microsoft through official support channels or via GitHub for clarification or resolution.

**Comment by alexbarth-maker** [comment]
@vynarim @AmarSaiRam 

We have the same issue. Seems quite similar to [[CoE Starter Kit - BUG] ISSUE Admin | Sync Template v3 (Custom Connectors) Flow run failed ](https://github.com/microsoft/coe-starter-kit/issues/7665 ) from 2024.

Back then it was stated that it is a problem on Microsoft's side. Hope this will be fixed soon.

**Comment by alexbarth-maker** [comment]
@vynarim @AmarSaiRam strange thing is that is works just fine when I re-submit the failed flow runs.

In the regular sync last night, it failed for 67 environments. I have re-submitted them manually (always 20 at bulk) and every single one suceeded and the action 'Get connection' ran without problems🤔

**Comment by mohamrizwa** [comment]
Hi @vynarim,
I’ve received confirmation from the customer that the issue has been resolved. Could you please verify on your end?
Refer to the following ticket for details:
https://github.com/microsoft/coe-starter-kit/issues/10248

**Comment by vynarim** [comment]
Hello, 
On my side everything seems to be back to normal since last monday, I have no more alert email
Thanks for this follow up

**Comment by mohamrizwa** [comment]
Hi @vynarim,
Thanks for confirmation,
Can we close this issue?

**Comment by alexbarth-maker** [comment]
For us, the error still exists. Our environment is in region EMEA.

**Comment by mohamrizwa** [comment]
Hi @alexbarth-maker,
I would request to share the below details for raising this to MS product team:
1. Environment URL
2. Environment ID
3. Region
4. Error Screenshot

**Comment by tomka75** [comment]
Newly opened here: https://github.com/microsoft/coe-starter-kit/issues/10360
Have the same issue.

**Comment by EggertN** [comment]
We have the same issure since 15th of October. 
core component version: 4.50.4
Governance Component: 3.27.3

**Comment by jesusfer** [comment]
As mentioned in #10360 I've had this issue in an environment in Europe, but not in an environment in US.

**Comment by tomka75** [comment]
Used Get-PowerAppConnector to get the informations. ChangedTime of the powerappsforappmakers connector is 2025-09-30T16:47:01.0815518Z in default env. in Germany.

**Comment by mohamrizwa** [comment]
As analyzed, we’ve confirmed this issue is related to the PowerApps product feature “Get Connectors.” We are already coordinating with the product team, and they have indicated that the resolution is expected by the end of this month.
To help them better understand the situation, please provide the following details:

Organization URL
Environment ID
Region
Screenshot of the error

**Comment by AmarSaiRam** [comment]
Dear User, 

We noticed that this issue has been pending for quite some time, and we have not received any recent updates from your end. In the absence of further communication, we are proceeding to close this ticket, assuming that your concerns have been addressed or resolved. 
If you continue to experience any difficulties related to this matter, please feel free to open a new support ticket. This will help us ensure prompt and effective assistance, rather than reopening the new Issue. 
Thank you for your understanding and cooperation. 

Best Regards, 
CoE Starter Kit Team

**Comment by EggertN** [comment]
we are still waiting for a solution. mohamrizwa has confirmed the error and found out what the problem is
