### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (Connection Identities) - Exceeded the maximum page count

### ISSUE THREAD

**Issue by adrianhh89** [microsoft/coe-starter-kit#10490]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

The Admin | Sync Template v4 (Connection Identities) flow is getting the following error:

Action ‘Get_Connections_as_Admin’ failed: The action ‘Get_Connections_as_Admin’ has an aggregated page count of more than ‘1000’. This exceeded the maximum page count ‘1000’ allowed.

Can something be done by the CoE team, or is this a product issue?

<img width="1544" height="554" alt="Image" src="https://github.com/user-attachments/assets/b5f3c9a3-1a67-41de-bda5-c43f87f3870b" />

### Expected Behavior

No error in execution

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.50.3

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Connection Identities)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by harini-2-y** [comment]
Hi @adrianhh89 ,
Apologies for the delayed response!

The error occurs due to a Power Automate pagination limit of 1,000 pages and has been addressed in CoE Starter Kit version v4.50.4 and later. Upgrading to this version will resolve the issue, as the updated flow is designed to stay within Power Automate’s pagination limits.
Please upgrade your Core solution to the latest version v4.50.6 and remove any unmanaged layers to ensure the fix is applied. Let us know if you need assistance with the upgrade process.

**Comment by adrianhh89** [comment]
Hello @harini-2-y,

Thank you for your response.

I am checking in our test environment, where we are installing the latest versions of CoE to verify that everything is correct in our tenant, that version 4.50.6 has exactly the same configuration: 1000 for the page size and the pagination threshold at 100,000 elements. 

Could this be something that will be updated in the next version?

**Comment by harini-2-y** [comment]
Hi @adrianhh89 ,
Thank you for verifying this. 
The updated configuration—reduced page size and removal of the pagination threshold setting—is already included in CoE Starter Kit version v4.50.4 and later. If you still see a page size of 1,000 and a threshold of 100,000 items, it likely means unmanaged layers are overriding the managed update. Please remove any unmanaged layers from the flow and reapply the upgrade. Once completed, the flow will reflect the correct settings and resolve the pagination issue.

**Comment by adrianhh89** [comment]
Hello @harini-2-y,

I am sure that I updated correctly to version 4.50.6 as I mentioned in my previous message, but I have ensured that there are no unmanaged layers and reinstalled that version, and I can assure you that it still shows 1000 for the page size and the pagination threshold at 100,000 items.

Please make sure this is corrected in the next version.

**Comment by harini-2-y** [comment]
Hi @adrianhh89 ,
Thank you for clarifying this.  Please update the configuration by reducing the page size from 1,000 to 250, as shown below:

     "$top": 250

 This change improves flow performance and prevents errors caused by pagination limits.

**Comment by adrianhh89** [comment]
Hello @harini-2-y ,

I changed it yesterday and haven't seen any more flow execution errors, so we can close the ticket.

Please note that the change does not yet appear in version 4.50.6.

Thank you for your help.

**Comment by harini-2-y** [comment]
Hi @adrianhh89 , 
Thank you for your patience. We will ensure this issue is fixed in the next release.
