### ISSUE TITLE
[CoE Starter Kit - BUG] Field "Flow Deleted" in Table Flows  change to No

### ISSUE THREAD

**Issue by Rudlstorfer** [microsoft/coe-starter-kit#10504]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

We are using the flow “CLEANUP – Admin | Sync Template v4 (Check Deleted)”. This flow runs every Sunday and marks flows that have been deleted from the original environment as “deleted” in the table "flow" column "Flow Deleted" within the CoE environment.

However, on Monday morning, the status of these flows changes back to “No”. When I run the “CLEANUP – Admin | Sync Template v4 (Check Deleted)” flow again on Monday, the flows are marked as “deleted” once more and on the next day it is "No" again.

I noticed that the “Flow Modified On” field is updated around 6:15 PM, but I have no clue which flow is causing this issue.

### Expected Behavior

The flow “CLEANUP – Admin | Sync Template v4 (Check Deleted)” works as expected, but somehow the value of the “Flow Deleted” field changes back to “No” every morning.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.50.6

### What app or flow are you having the issue with?

unknow 

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Delete a flow
2. Run check deleted
3. Wait for next Day

**Comment by Rudlstorfer** [comment]
will the [fix ](https://github.com/microsoft/coe-starter-kit/pull/10508) be included in the next release?

**Comment by AmarSaiRam** [comment]
Hi @Rudlstorfer 
Removed explicit deleted field assignments from update operations in 11 sync flows:

SYNCHELPER-CloudFlows (2 occurrences)
SYNCHELPER-Apps (2 occurrences)
AdminSyncTemplatev4ModelDrivenApps (2 occurrences)
AdminSyncTemplatev4Desktopflows (2 occurrences)
AdminSyncTemplatev4CustomConnectors (8 occurrences)
AdminSyncTemplatev4Portals (2 occurrences)
AdminSyncTemplatev4Solutions (2 occurrences)
AdminSyncTemplatev4Driver (2 occurrences)
AdminSyncTemplatev4AiModels (2 occurrences)
AdminSyncTemplatev4BusinessProcessFlows (2 occurrences)
AdminSyncTemplatev3FlowActionDetails (1 occurrence)

**Comment by AmarSaiRam** [comment]
Hi @Rudlstorfer ,
Root Cause Analysis
The issue you're experiencing is a conflict between two flows that are operating on the same admin_flowdeleted field:

1. CLEANUP - Admin | Sync Template v4 (Check Deleted)
Runs weekly (Sundays in your case)
Sets admin_flowdeleted to Yes for flows that no longer exist in the tenant
2. Admin | Sync Template v4 (Flows)
This is the main inventory sync flow
Runs regularly (likely daily or when triggered)
Re-discovers flows and resets the admin_flowdeleted field back to "No"
The problem occurs because:

The cleanup flow correctly marks deleted flows on Sunday
On Monday morning (around 6:15 PM based on your observation of "Flow Modified On"), the main sync flow runs
The sync flow attempts to re-inventory flows and inadvertently resets the deleted flag back to "No"
Solution
Here are the recommended solutions to fix this issue:

Solution 1: Verify the Flow Is Actually Deleted
First, confirm that the flow is truly deleted from the original environment:

Navigate to the Power Automate portal
Go to the environment where the flow originally existed
Search for the flow ID to verify it no longer exists
If it still exists, the flow is not actually deleted
Solution 2: Check and Configure Environment Variables
Ensure your sync flows are configured correctly:

Go to Power Apps → Solutions → Center of Excellence - Core Components
Check the Admin | Sync Template v4 (Flows) flow settings
Verify that the flow has proper logic to skip flows that are marked as deleted
Solution 3: Identify the Conflicting Flow
Based on your observation that "Flow Modified On" updates around 6:15 PM, follow these steps:

Check the run history of Admin | Sync Template v4 (Flows)
Look for runs that occur around 6:15 PM (when the field changes)
Review the flow logic to see if it's resetting the admin_flowdeleted field
[[CoE Starter Kit - BUG] Field "Flow Deleted" in Table Flows change to No#10504](https://github.com/microsoft/coe-starter-kit/issues/10504)
microsoft/coe-starter-kit · AmarSaiRam closed on Jan 1, 1
Assignee avatar
Solution 4: Modify the Sync Flow Logic
The main sync flow needs to be updated to respect the deleted flag. Add a condition to skip flows where admin_flowdeleted = Yes:

Open Admin | Sync Template v4 (Flows)
Find the section where flows are being updated
Add a filter condition:
Code
Filter flows where admin_flowdeleted is not equal to Yes (true)
This prevents the sync flow from resetting deleted flows
Solution 5: Adjust Flow Execution Schedule
Consider adjusting the cleanup flow schedule:

Run CLEANUP - Admin | Sync Template v4 (Check Deleted) AFTER the daily sync flows complete
This ensures deleted flows are marked after the sync has run
Alternatively, run it daily instead of weekly to continuously mark deleted flows
Solution 6: Investigate the 6:15 PM Update
Since you mentioned the "Flow Modified On" field updates around 6:15 PM:

Check all scheduled flows that run around that time

Common suspects:

Admin | Sync Template v4 (Driver) - triggers other sync flows
Admin | Sync Template v4 (Flows) - main flow inventory sync
Any custom flows that update flow records
Review the flow run history for flows running at 6:15 PM

Look for any Patch or Update operations on the admin_flows table

Recommended Immediate Actions
Check flow run history around 6:15 PM (when the field changes):

Go to Cloud flows in your CoE environment
Filter by run time around 6:15 PM
Identify which flow is modifying the records
Manually verify deleted flows:

Navigate to Dataverse → Tables → admin_flows
Filter for flows where admin_flowdeleted = Yes
After the next Monday morning reset, check if those same flows were reset to "No"
Add logging to identify the culprit:

Add a Compose action in the sync flows to log when admin_flowdeleted is being modified
Review logs to see which flow is changing the value

**Comment by AmarSaiRam** [comment]
Dear User,

We noticed that this issue has been pending for quite some time, and we have not received any recent updates from your end. In the absence of further communication, we are proceeding to close this ticket, assuming that your concerns have been addressed or resolved.
If you continue to experience any difficulties related to this matter, please feel free to open a new support ticket. This will help us ensure prompt and effective assistance, rather than reopening the new Issue.
Thank you for your understanding and cooperation.

Best Regards,
CoE Starter Kit Team

**Comment by Rudlstorfer** [comment]
Hi @AmarSaiRam,
I can confirm that the flow has been completely deleted from the original environment.
The Admin | Sync Template v4 (Flows) looks as shown in the image:

<img width="1004" height="600" alt="Image" src="https://github.com/user-attachments/assets/50d51634-5ad2-4afe-bbac-4a6e9971ffa1" />

I will stop the Admin | Sync Template v4 (Flows) until Monday, and then I can check whether this flow is causing the error.

**Comment by Rudlstorfer** [comment]
update on the last post i stopt the Admin | Sync Template v4 (Flows). After the run of the flow CLEANUP – Admin | Sync Template v4 (Check Deleted) the flow was marked as deleted, but on monday morning the flow was marked as not deleted

<img width="1656" height="202" alt="Image" src="https://github.com/user-attachments/assets/1942d5ab-55fc-4cfc-ab11-9fec6a770c95" />

<img width="1004" height="520" alt="Image" src="https://github.com/user-attachments/assets/655de77c-2b95-4a17-b802-58002c8c681e" />

**Comment by Rudlstorfer** [comment]
i also performed the update to Version 4.50.9 but the issue is still here. 
Any further advice how to tackle this issue.
