### ISSUE TITLE
[CoE Starter Kit - BUG] Error turning on CLEANUP - Admin | Sync Template v3 (Check Deleted)

### ISSUE THREAD

**Issue by osbornecc** [microsoft/coe-starter-kit#1190]
### Describe the issue

I just went through the steps to Update from an older version of Core Components (and Audit Logs) to Core Components 3.11.  Full disclosure, I did the Update steps to break the dependencies to get to the August release, then I immediately turned around and performed Updates (not Upgrades) to get to the September release, version 3.11.

I had already removed unmanaged layers of all Flows I had customized prior to Updating to 3.11.  Then I performed the steps in https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows

When I get to the part where I need to turn on  CLEANUP - Admin | Sync Template v3 (Check Deleted), doing so throws an error:

Flow save failed with code 'WorkflowUnderWrongSubscription' and message 'The child workflow '/subscriptions/xxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Logic/workflows/xxxxxx' must be under the same subscription as the parent workflow. Parent workflow is under subscription 'xxxxx' while child workflow is under subscription 'xxxxxx'.'.

I tried editing each flow just to save it, I edited the "details" where it shows the plan and just saved that.  Nothing seems to get rid of that error.  Is it just me?
Thanks!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.11

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

**Comment by Jenefer-Monroe** [comment]
Hello you need to update and turn on the child flows for this flow now. Please see [Update and turn on child flows](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows)

**Comment by osbornecc** [comment]
Hi Jenefer,
Yes, I saw those instructions during the update process.  They were performed as listed before I tried turning on the "check deleted" flow.  

![image](https://user-images.githubusercontent.com/50427725/134016206-bfcf75c3-9a9e-45e0-bdfb-5fe42d695d56.png)
![image](https://user-images.githubusercontent.com/50427725/134016224-aeb18609-f55c-4c7c-8789-3d182c669f02.png)

Friday, I even turned them off/on again, hit Edit and then saved (to try to kick it into gear), and re-checked the run only user setup.  The "check deleted" flow still throws the subscription error even this morning.

Thanks

**Comment by osbornecc** [comment]
Oh, in case it makes a difference for this issue:  we are in GCC.
Thank you.

**Comment by Jenefer-Monroe** [comment]
Is the flow owner / the identity of the connectors different for the Check Deleted and its helpers?

**Comment by osbornecc** [comment]
No, everything is owned by me.

**Comment by Jenefer-Monroe** [comment]
Have you done a save-as for the parent or the children? Or are they both still running from within the solution folder. 
Can you check to see if unmanaged layers exist on the parent?

**Comment by osbornecc** [comment]
Hi Jenefer,
Thanks for all the attempts!

I did have an unmanaged layer originally on that parent flow.  After updating to August's version, I removed the unmanaged layer.  Then I updated to September's version (3.11) without that unmanaged layer.

No, I have not gone through and done "save as" on any of them, as I'm hoping to not have to do that :-)

**Comment by osbornecc** [comment]
One thing to note in case it wasn't clear in my original description:  When I updated to August's version, I removed unmanaged layers of everything I had touched....but I did not go through the setup steps.  I simply turned right around and applied 3.11.  Once I got to 3.11 that's when I started performing the setup steps.

**Comment by Jenefer-Monroe** [comment]
Can you share a picture of the run-only settings for the child flows?

**Comment by osbornecc** [comment]
Sure.  Here is one of the HELPER flows as an example.  They are all like this.

![image](https://user-images.githubusercontent.com/50427725/134022564-3e5ec89f-276f-49c7-a4ee-74d5d6696c1a.png)

As you can see, the Run Only Users section looks empty.  But I had previously edited it as described in the steps.  Hitting Edit again shows they are all linked to my account

![image](https://user-images.githubusercontent.com/50427725/134022707-b7485ab1-e67f-4a23-86f6-87fea937075f.png)

**Comment by Jenefer-Monroe** [comment]
And can you please validate this for all the child flows? 
![image](https://user-images.githubusercontent.com/89584709/134025066-15d39f29-a5c0-44e8-9ff1-80132d6f61f0.png)

**Comment by osbornecc** [comment]
Hi Jenefer,

I've confirmed all of the child flows look similar to my first example.  However, there is one exception:  HELPER - ObjectOperations

![image](https://user-images.githubusercontent.com/50427725/134027492-f13696cd-7fab-43ae-adb4-dd40947cd78c.png)
![image](https://user-images.githubusercontent.com/50427725/134027534-16888a00-40ac-4fbf-b875-523d7a097730.png)

**Comment by Jenefer-Monroe** [comment]
Yes that is expected. 

I'm really not sure what to do here. From my research, this is only expected to happen if you are using parent/child flows across solutions (which you confirmed above you are not, both are operating out of Core) or if these settings are not complete (and for that I usually see a different error anyway). 

I have seen some people face this in their own solutions and exporting/importing fixed, implying there is just some product bug here. But I dont think you can do that since you are managed. 

Let me see if I can find something else to try.

**Comment by osbornecc** [comment]
I have to ask since it has come up before.  Could there be something with us being GCC?
Thanks!

**Comment by Jenefer-Monroe** [comment]
I've reached out to our GCC expert to see if they are able to use the **_check deleted_** flow now with these child flows added

**Comment by Jenefer-Monroe** [comment]
Yes that's my guess as well. Which is why I was asking about the save-as. I've read of cases where some product bug made these not work exactly as you described and the person had to re-create their solution. But thats a thing you cant do since you are managed. 
I did validate that this is working for other GCC intalls though. 

You may have to create a support ticket for help, and give them the detective work you have right there. 
And I will keep investigating on my side too.

**Comment by osbornecc** [comment]
I see that Core Components 3.12 is available.  I'm going to apply that and see if that makes my problems magically go away.

**Comment by osbornecc** [comment]
Nope.  OK resorting to support ticket.

**Comment by osbornecc** [comment]
Hi Jenefer,

I opened a support case.  This community post was mentioned:  https://powerusers.microsoft.com/t5/Building-Flows/Flow-cannot-use-a-Child-Flow-because-they-are-in-different/td-p/510064

Do you think that could be what's going on with my solution?  That the flows were created in different places?

Thanks,

**Comment by Jenefer-Monroe** [comment]
These flows were all created in the Core solution, and you are the only person facing this, so I dont know that there is  a wide spread thing we can do here to fix.  

One thing we could try next release would be to delete these flows and see if they get put in correctly with the new install. We can hold this open and try that with the Oct release.

**Comment by osbornecc** [comment]
Thank you for confirming.

**Comment by osbornecc** [comment]
There is one thing I'm noticing.  Every time I try to re-import the solution (and force overwrite), the Check Deleted flow and all of the different HELPER and CLEANUP HELPER flows have one unmanaged solution layer.  I don't make changes, but it's there.  The publisher is default for my environment, while the publisher for all other objects is Power Platform Admin.

I'm trying to remove these unmanaged layers to see if that helps.  When I look at the solutionid between the layers, they are different.  

Could this be part of the issue?

**Comment by osbornecc** [comment]
I tried creating a new solution, saving the child flows as copies and creating the parent Check Deleted flow inside the solution and using the clipboard to copy all the steps.  The new Check Deleted won't save when I copy over the first step that includes Dataverse connections.

Is there a package you could give me to use while we wait for the October release?  Or something else to just get me by?  I really do not want to start completely over and lose my data.

I'm sorry.

**Comment by Jenefer-Monroe** [comment]
Don't apologize. I appreciate your efforts and hope we can resolve this! 
I suggest we try to delete all these Check Deleted flows and then upgrade/overwrite via classic

Can you create a new flow in your CoE environment, and have it just be a single action as shown here with the [Remove Flow as Admin](https://docs.microsoft.com/connectors/microsoftflowforadmins/#remove-flow-as-admin) action
![image](https://user-images.githubusercontent.com/89584709/134514292-ae427e4d-9679-4776-aadd-cdc40ea4fb89.png)

Then for all the Check Deleted flows, get the envt name and flow name by going to the flow and getting them from the URL: 
![image](https://user-images.githubusercontent.com/89584709/134514826-9ddb3aa3-ba7d-4872-84a7-d43defc6b23b.png)

Run that for all these flows:

- HELPER - CloudFlowOperations
- HELPER - CanvasAppOperations
- HELPER - ObjectOperations
- CLEANUP HELPER - Check Deleted (Canvas Apps)
- CLEANUP HELPER - Check Deleted (Cloud Flows)
- CLEANUP HELPER - Check Deleted (Model Driven Apps)
- CLEANUP HELPER - Check Deleted (PVA)
- CLEANUP - Admin | Sync Template v3 (Check Deleted)

Hopefully that works to delete these all even though you are managed. Then try the upgrade/overwrite again.

**Comment by Jenefer-Monroe** [comment]
OK here's a last idea to try. 
Upgrade / overwrite with this interim solution. I deleted the check deleted flow from it, and its a capture of the toolkit before the helpers were added. 

No Check Deleted Flows: [CenterofExcellenceCoreComponents_3_12_1_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7218696/CenterofExcellenceCoreComponents_3_12_1_managed.zip)

Then open the solution and make sure none of them are there. They should be removed if not present in the installing solution files. 

If they are gone, upgrade with this one which has them included again:
[CenterofExcellenceCoreComponents_3_13_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7218676/CenterofExcellenceCoreComponents_3_13_managed.zip)

**Comment by osbornecc** [comment]
This just gets weirder and weirder.  

OK, I had to Update when importing 3.12.1 (not classic view).  I had tried Upgrade and Upgrading in classic and it was unhappy, but I forget why.  This resulted in two solutions

![image](https://user-images.githubusercontent.com/50427725/134547688-65d4bbeb-9126-46fc-86a8-b724fd3e88f1.png)

The one in orange is as you described:  no check deleted flows.  
The one in yellow is the original.  Says it's updated but it still has the check deleted flows.

Trying to Upgrade/Update in any view to 3.13 tosses an error.  The error is that it cannot find the Connection Reference "admin_CoECoreHTTPAZUREAD."  

Well....the solution highlighted in orange does not have that connection reference.  The original one in yellow does.

¯\\_(ツ)_/¯

**Comment by osbornecc** [comment]
Last hail mary:  I took an environment backup pre-updating the CoE.  I'm going to restore and try updating fresh.

**Comment by osbornecc** [comment]
While the restore runs, I'd like to confirm something.  We were originally on Core 2.0 and Audit Logs 1.40.  When I go to upgrade to  Core 3.13 and Audit Logs 2.4, I still need to do the steps like so?

1. Update (not upgrade) Audit Logs
2. Upgrade Core

I got that order from #1005 

Thanks!

**Comment by Jenefer-Monroe** [comment]
no we believe we have fixed that dependency problem. you should be able to start with Core again, as would be normally expected.

**Comment by osbornecc** [comment]
Something is still messed up.  I removed all the managed layers after performing the restore, then got the solutions upgraded.  All flows were Off.  I went through the child flows, updated them and turned them on.  The Check Deleted still gets the wrong subscription error.  The subscription guids are the same as before.

So I deleted all my connections, edited each child flow to reconnect and then edited the Check Deleted flow to reconnect.  I can't even save the Check Deleted because of the subscription error.

Should I re-do the solutions but in Classic view to force the updates?

**Comment by osbornecc** [comment]
So, what I'm really worried about losing is the Audit Log historical data.  Is it possible for me to delete the Core Components solution but **leave** Audit Logs?  Then re-import Core fresh?

I'm pretty sure that won't mess up the Audit Log data, but just double checking.
Thanks.

**Comment by Jenefer-Monroe** [comment]
Actually it will. Core is where the audit logs data is stored. 

You only use Core + Audit logs correct? And you don't have any concerns about losing other extended data in the environment you may have used? (ex setting capacity limits per environment). 
If thats the case, then I think I can walk you through how you start from scratch and then get your audit log data restored. 

But before we do that, perhaps it would be best to create a new CoE environment and install core fresh, to be sure it will even work in a clean envt.

**Comment by osbornecc** [comment]
That's right, I forgot Core is the solution where the tables live.

Yes, we only use Core + Audit right now.  I will attempt Core in a fresh environment like you suggested, then we can move onto restoring the data.  

Thank you!

**Comment by osbornecc** [comment]
Sorry for taking so long.  Things were a bit slow.

Anyway, importing Core fresh into a new environment successfully lets the Check Deleted flow get flipped on.  It's running now.

As for migrating the audit log data, is this basically what I'll need to do?  
https://docs.microsoft.com/en-us/powerapps/developer/data-platform/dataverse-odata-dataflows-migration
Thank you

**Comment by osbornecc** [comment]
I'm almost done getting the Core data pulled into the new environment.  What were your thoughts on the Audit Log restoration?
Thanks!

**Comment by osbornecc** [comment]
Finally, all of the initial Core data is now in the newly created environment.  I have yet to import the Audit Logs solution into this environment.  Should we restore the Audit log data from the original environment first?
Thank you.

**Comment by Jenefer-Monroe** [comment]
You can import the audit log data using he tool you reference above as we don't need to preserve the GUID. 
This will get you everything working again except the **_App Last Launched On_** field. 
For this you will need to write a flow to repopulate from the audit log itself.

**Comment by Jenefer-Monroe** [comment]
So I have a flow written to do this for you. I'm running a last test on it to make sure it works but wanted to send it to you so that you dont also author the same thing :)
[ProductBugDemo-getflowaftergetflowsfails_20210702144440.zip](https://github.com/microsoft/coe-starter-kit/files/7247221/ProductBugDemo-getflowaftergetflowsfails_20210702144440.zip)

I'll ping you in the morning to let you know if it worked on my full test tenant run or not.

**Comment by osbornecc** [comment]
Thank you for doing that, it is much appreciated!

My data import is still chugging along so yes, touching base in the morning is a good idea.

**Comment by Jenefer-Monroe** [comment]
ok that flow seems to work. So after you migrate your audit log data into the new CoE, you can import this flow into the new CoE environment and run it. This should re-populate the last launched field and your CoE should be working again.

**Comment by osbornecc** [comment]
OK just to clarify, the flow from the package has this
![image](https://user-images.githubusercontent.com/50427725/135286431-fb2e1c41-0236-400e-8ce4-a8111e0e41ab.png)

Is that the correct set of steps to update App last launched?
Thanks,

**Comment by Jenefer-Monroe** [comment]
Nope I attached the wrong flow! OOPS! Hold on

**Comment by Jenefer-Monroe** [comment]
Flow looks like this: 
![image](https://user-images.githubusercontent.com/89584709/135288286-e991dda9-8acd-48c2-aac9-3cf5a1751258.png)

And is now actually attached:
[rehydrateapplastlaunchedfield_20210929142525 (1).zip](https://github.com/microsoft/coe-starter-kit/files/7252728/rehydrateapplastlaunchedfield_20210929142525.1.zip)

Fixing above and hiding your comment, in case folks look here for the solution to avoid confusion :)

**Comment by osbornecc** [comment]
That technically worked.  But it only updated some of my apps, and for sure I know at least one last launched date is wrong.  When I look at the last condition it only hit 500 rows.  I think the step that gets Audit Log data only pulls 500 rows.

![image](https://user-images.githubusercontent.com/50427725/135305946-20b22530-c86c-4112-a4da-8572e254c080.png)

When I did the audit log data import, there were 658,000+ rows of audit log data.  We have one app that 5000 people must launch daily.

Is there a way to filter/paginate?

**Comment by Jenefer-Monroe** [comment]
hmm it iterated more than that for me. so I'm not sure what happened there. 
![image](https://user-images.githubusercontent.com/89584709/135311892-80b227f1-8766-452a-abde-a8a2fc869800.png)

If this flow doesnt work for you, the other option would be something like this: 
- export the power apps table from the old CoE environment
- create a table of the data (the table feature in Excel)
- load that file into SPO
- Create a flow which iterates all the apps (like the above), and look for that app the excel table
- Get the last launched value from excel and write it to the new CoE database.

**Comment by osbornecc** [comment]
Ahh, well I think because my audit log table has so many rows it wasn't grabbing everything!  I was able to tweak your flow to get the data I needed.

I basically moved the filtering and audit log listing into the "for each" and I sorted the audit log data by descending date (in case there were so many pulled in!)  Here is a high level of my edits.  
![image](https://user-images.githubusercontent.com/50427725/135316045-93e05941-77f3-44d7-a34a-852a51a5466e.png)

When it ran, all the apps I expected to have launch dates from 9/16/2021 were updated.  

Thank you so much for your help on this!  I think we can say we're finally done.

**Comment by Jenefer-Monroe** [comment]
I feel like be both earned a soda or a beer or whatever is celebratory for you :) 

I suggest you use the [backup/restore feature](https://docs.microsoft.com/en-us/power-platform/admin/backup-restore-environments#:~:text=Go%20to%20Environments%20%3E%20%5Bselect%20an,restore%2C%20and%20then%20select%20Continue.) for this new CoE environment before upgrading in Oct.

**Comment by Jenefer-Monroe** [comment]
Closing out this issue now.
