### ISSUE TITLE
[CoE Starter Kit - QUESTION] Set up embedded apps in Power BI

### ISSUE THREAD

**Issue by Shinji-Suzuki** [microsoft/coe-starter-kit#2377]
### What is your question?

I use translation software to make inquiries.
I may not speak correct English.

I have installed the CoE Starter Kit, but "Cloud flow Deteil" and "App Detail" do not work properly.
![SS](https://user-images.githubusercontent.com/100173189/161945416-97043f1f-cca7-4ce3-984a-f5dad89c8136.png)
![SS2](https://user-images.githubusercontent.com/100173189/161945702-1aa89a09-8ab0-4e04-b453-5264fd09350b.png)

I asked "https://github.com/microsoft/coe-starter-kit/issues/2102" before, but is it related to these?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.20.6

**Comment by manuelap-msft** [comment]
Hello,

you have to follow these steps to configure the embedded apps:
https://docs.microsoft.com/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard

Make sure the apps called **Admin - Access this Flow** and **Admin - Access this app** are shared with the user accessing the Power BI. 

If you've completed these steps and it stil doesn't work, could you help translate the error message that you see on the screen as that may help us find the root cause?

Thank you
Manuela

**Comment by Shinji-Suzuki** [comment]
Thank you for contacting me.
We have implemented the procedure for the URL you notified us, but it is not working.
Admin --Access this Flow and Admin --Access this app are also shared.

No error is displayed for "App Detail". I think the problem in the first place is that it cannot be linked with environmental data.
"Cloud flow Deteil" had the following error in "Admin --Access this Flow".
-----------------------------------------
Application '44b045f3-6ba3-4f3e-9347-6d6e876eed6c' was not found in tenant'c26d3ea9-9778-487b-8a9b-8b0243c534ad'.
Session ID: 369f315b-4461-4d49-9f9e-fe367a1f48dd
-----------------------------------------
Is there anything you can tell from this information?

**Comment by manuelap-msft** [comment]
We have seen this issue once before: https://github.com/microsoft/coe-starter-kit/issues/2186

And the reason there was the person was not signed into Power BI Desktop with the right user credentials. Please make sure you are signed into Power BI Desktop with the same user credentials that the app is shared with.

**Comment by Shinji-Suzuki** [comment]
Thank you for contacting me.
I would like to review the error of "Admin-Access this Flow" of "Cloudflow Deteil".
Do you have any idea about the situation of "App Detail"?

**Comment by dougmaster-77** [comment]
@manuelap-msft 
We are experiencing the same issue as @Shinji-Suzuki after the April update of the CenterofExcellenceCoreComponents_3.36_managed and the Power Bi reports. We rolled back the update of the PowerBI dashboard and every thing works fine again, but we don't know what is going wrong here.

**Comment by manuelap-msft** [comment]
@dougmaster-77 If you're updating to use the new version of the dashboards, you'll have to perform these steps again https://docs.microsoft.com/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard - can you confirm you've done that, and are still seeing issues? We do not repo this in our tenant unfortunately.

**Comment by dougmaster-77** [comment]
@manuelap-msft tnxs work perfectly now

**Comment by taiki-yoshida** [comment]
@Shinji-Suzuki  さん、はじめまして。Manuela の同僚の吉田と申します。お問い合わせの事象ですが、過去に同じ事象が発生した原因として、以下の3点が考えられます。
- Power BI 上で埋め込まれたアプリが正しく設定されていない場合
- 管理者により直接埋め込まれたアプリが共有されていない場合（例えば、ソリューションに該当のアプリが含まれていることを確認した場合でも、管理者はPower BIで動作させるためにはそのアプリを共有する必要があります）
- Power BI 上でのログイン情報が管理者とは別のユーザーに切り替わっている、もしくはログインがされていない
上記3点にお心当たりございますでしょうか？

**Comment by manuelap-msft** [comment]
Hello @Shinji-Suzuki,

we were just made aware of a product bug which impacts the Power Apps visual in Power BI. This product bug impacts older versions of Power BI desktop. Customers will need to upgrade to version 2.2.19 which is included in latest version of Power BI desktop 2.103.881.0.

You may be on an older version of Power BI Desktop, and need to upgrade to the latest version.

Thank you
Manuela

**Comment by Shinji-Suzuki** [comment]
@manuelap-msft @taiki-yoshida 
I am sorry for contacting you late.

I reconfigured the settings to confirm the points I received.
Then, I found a problem in the first place, so let me ask you a question.
When I set "Admin --Access this app", I was prompted to transport it to PowerApps Studio to make a data connection, but I got an error after moving to the site.
![SS1](https://user-images.githubusercontent.com/100173189/163137711-5d7aa486-f586-4ba2-b0f5-afa758886532.png)
↓
![SS2](https://user-images.githubusercontent.com/100173189/163138500-422ecd44-004f-424a-bec1-3442c622d985.png)
Do you know the solution to this problem?

I don't think the next question is at the level of asking now, I'm sorry.
I couldn't find the "Power Apps visual" in the visualization in step 12, has it been renamed?
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard

Thank you
Shinji Suzuki

**Comment by taiki-yoshida** [comment]
@Shinji-Suzuki that error says that you are missing the environment specified. That may be happening if you dont have access to the environment. Can you check that the user you are using to set this has access to the environment you installed the CoE Starter kit? If you are using some other account, it may show the error.

表示されているエラーによると、環境へのアクセス権が無いように見受けられます。現在設定を試されているアカウントと、CoE Starterkit をインストールしたアカウントと同じものをご利用でしょうか？もし別のアカウントで運用されていたりする場合に発生する可能性がございます。

**Comment by Shinji-Suzuki** [comment]
@taiki-yoshida 
Yes. I'm trying the procedure from the same user who installed the CoE Starter Kit, but I'm getting an error.

はい。CoEスターターキットをインストールした同じユーザから手順を試していますが、エラーが発生しています。

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
