### ISSUE TITLE
[CoE Starter Kit - BUG]: Power BI template fails to load ("Object reference not set to an instance of an object")

### ISSUE THREAD

**Issue by mschaefer85** [microsoft/coe-starter-kit#547]
**Describe the bug**
We're unable to load the Power BI template. After a few minutes of loading, it shows the error "Something went wrong: Object reference not set to an instance of an object".

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core
 - Version: 2.1.6.
 - App or Flow [e.g. Sync Template (v2)]: Neither, it's the Power BI template "Dashboard-PowerPlatformAdminDashboard-2021-04-08.pbit"

**To Reproduce**
1. Install the Core Components of the CoE Starter Kit.
2. Open Power BI Desktop.
3. Click on File -> Import -> Power BI template
4. Choose Dashboard-PowerPlatformAdminDashboard-2021-04-08.pbit
4. Enter the OrgUrl without "http://" as a prefix or "/" as a postfix.
5. Click on Load.
6. Wait for several minutes.
7. See error.

**Expected [behavior**]
I'd expect the Power BI report to load.

**Screenshots**
![image](https://user-images.githubusercontent.com/10259284/120316571-dca08380-c2dd-11eb-941b-27dae46dc25d.png)

**Additional context**
1. The Power Platform we're working on is pretty large, with over 700 environments. 
2. The error details are as follows:

Error details
<details>
Feedback Type:
Frown (Error)

Error Message:
Object reference not set to an instance of an object.

Stack Trace:
Microsoft.Mashup.Host.Document.SerializedException
   at Microsoft.Mashup.Evaluator.ChannelMessenger.CreateChannel()
   at Microsoft.PowerBI.Client.OleDbProvider.PowerBIMashupDataSource.EvaluationSession.Dispose()
   at Microsoft.Mashup.Host.ProviderShared.PackageMashupEvaluator.<>c__DisplayClass7_0.<Evaluate>b__1(Object o)
   at Microsoft.Mashup.Evaluator.Interface.InvokeManyAction`1.CheckDone()
   at Microsoft.Mashup.Evaluator.Interface.InvokeManyAction`1.InvokeMany(T value)
   at Microsoft.Mashup.OleDbProvider.DataHost.MashupEvaluator.<>c__DisplayClass4_1.<Evaluate>b__1()
   at Microsoft.Mashup.OleDbProvider.DataHost.AsyncResultIDataReaderSourceHelper.InvokeThenOnDispose(Action`1 callback, AsyncResult`1 result, Action action)
   at Microsoft.Mashup.OleDbProvider.DataHost.MashupEvaluator.<>c__DisplayClass4_0.<Evaluate>b__0(EvaluationResult2`1 result)
   at Microsoft.Mashup.Evaluator.Interface.EvaluationResultExtensions.InvokeThenOnDispose(Action`1 callback, EvaluationResult2`1 result, Action action)
   at Microsoft.Mashup.Evaluator.Interface.EvaluationResultExtensions.InvokeThenOnDispose[T](Action`1 callback, EvaluationResult2`1 result, Action action)
   at Microsoft.Mashup.Evaluator.LimitedDocumentEvaluatorFactory.Evaluation`1.Complete(EvaluationResult2`1 result)
   at Microsoft.Mashup.Evaluator.Interface.EvaluationResultExtensions.InvokeThenOnDispose(Action`1 callback, EvaluationResult2`1 result, Action action)
   at Microsoft.Mashup.Evaluator.Interface.EvaluationResultExtensions.InvokeThenOnDispose[T](Action`1 callback, EvaluationResult2`1 result, Action action)
   at Microsoft.Mashup.Evaluator.DocumentEvaluator.<>c__DisplayClass7_0`1.<BeginGetResult>b__0(EvaluationResult2`1 result)
   at Microsoft.Mashup.Evaluator.Interface.EvaluationResultExtensions.InvokeThenOnDispose(Action`1 callback, EvaluationResult2`1 result, Action action)
   at Microsoft.Mashup.Evaluator.Interface.EvaluationResultExtensions.InvokeThenOnDispose[T](Action`1 callback, EvaluationResult2`1 result, Action action)
   at Microsoft.Mashup.Evaluator.LimitedDocumentEvaluatorFactory.Evaluation`1.Complete(EvaluationResult2`1 result)
   at Microsoft.Mashup.Evaluator.RemoteDocumentEvaluator.RemoteEvaluation`1.TryComplete(EvaluationResult2`1 result)
   at Microsoft.Mashup.Evaluator.RemoteDocumentEvaluator.RemoteEvaluation`1.TryCompleteWithException(Exception exception)
   at Microsoft.Mashup.Evaluator.RemoteDocumentEvaluator.RemoteEvaluation.Evaluate(Boolean enableFirewall)
   at Microsoft.Mashup.Evaluator.RemoteDocumentEvaluator.EvaluationThread(Object state)
   at Microsoft.Mashup.Evaluator.GlobalizedEvaluatorThreadPool.<>c__DisplayClass1_0.<Start>b__0(Object s)
   at Microsoft.Mashup.Evaluator.EvaluatorThreadPool.EvaluatorThread(Object state)
   at Microsoft.Mashup.Evaluator.SafeThread2.<>c__DisplayClass3_0.<CreateThreadStart>b__0(Object o)
   at Microsoft.Mashup.Evaluator.SafeThread2.<>c__DisplayClass9_0.<CreateAction>b__0(Object o)

Stack Trace Message:
Object reference not set to an instance of an object.

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace, String exceptionMessage)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.GetStackTraceInfo(Exception e)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.ReportException(IWindowHandle activeWindow, IUIHost uiHost, FeedbackPackageInfo feedbackPackageInfo, Exception e, Boolean useGDICapture)
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.<>c__DisplayClass15_0.<HandleException>b__0()
   at Microsoft.Mashup.Host.Document.SynchronizationContextExtensions.<>c__DisplayClass2_1.<SendAndMarshalExceptions>b__0(Object null)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.UI.Windows.DialogWindowBase.ShowModal(IWindowHandle windowHandle)
   at Microsoft.PowerBI.Client.Windows.CefHtmlForm.<>n__1(IWindowHandle windowHandle)
   at Microsoft.PowerBI.Client.Windows.CefHtmlForm.<>c__DisplayClass34_0.<ShowModal>b__0()
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.PowerBI.Client.Windows.CefHtmlForm.ShowModal(IWindowHandle owner)
   at Microsoft.Mashup.Client.UI.Shared.Ux.WindowService.ShowDialog(IDialog dialog)
   at Microsoft.PowerBI.Client.Windows.FloatingDialog.KoLoadToReportDialog.TryShowDialog(Report report, IExceptionHandler exceptionHandler, IPowerBIWindowService windowService, IQueryServices queryServices, IModelingService modelingService, LocalizedString title, LoadToModelContext loadToModelContext)
   at Microsoft.PowerBI.Client.Windows.FloatingDialog.KoLoadToReportDialog.<>c__DisplayClass16_0.<TryShowDialogForQueries>b__0()
   at Microsoft.PowerBI.Client.Windows.Report.<>c__DisplayClass60_0`1.<SynchronizeLooselyWithQueries>b__0()
   at Microsoft.PowerBI.Client.Windows.Report.<SynchronizeLooselyWithQueriesAsync>d__61`1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.Report.SynchronizeLooselyWithQueriesAsync[T](Func`1 getTask)
   at Microsoft.PowerBI.Client.Windows.Report.SynchronizeLooselyWithQueries[T](Func`1 action)
   at Microsoft.PowerBI.Client.Windows.FloatingDialog.KoLoadToReportDialog.TryShowDialogForQueries(Report report, IExceptionHandler exceptionHandler, IPowerBIWindowService windowService, IQueryServices queryServices, IEnumerable`1 queriesToApply, String loadReason, LocalizedString title, QueryLoadMode queryLoadMode, Action`1 beforeSchemaSyncCallback, Action`1 afterSchemaSyncCallback)
   at Microsoft.PowerBI.Client.Windows.Services.TemplateManager.PromptForParametersAndCredentials(IPowerBIWindowService windowService, IQueryServices queryServices, IExceptionHandler exceptionHandler, String filePath, Report templateReport, Boolean allCredentialsSatisfied, Boolean& editQueries)
   at Microsoft.PowerBI.Client.Windows.Services.TemplateManager.TryImportTemplate(IPowerBIWindowService windowService, IQueryServices queryServices, IExceptionHandler exceptionHandler, TelemetryUserActionId entryPoint, Boolean& editQueries, String filePath)
   at Microsoft.PowerBI.Client.Windows.Commands.ApplicationCommands.DataImportCommands.ImportTemplate(IPowerBIWindowService windowService, IExceptionHandler exceptionHandler, ImportTemplateParameters parameters)
   at Microsoft.PowerBI.Client.Windows.Commands.CommandFactory.<>c__DisplayClass13_1`1.<FromSyncHandlers>b__1()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Windows.Commands.CommandFactory.ExecuteWithExceptionHandler(Action executeMethod, IExceptionHandler exceptionHandler, String telemetryCommandName)
   at Microsoft.PowerBI.Client.Windows.Commands.CommandFactory.<>c__DisplayClass13_0`1.<FromSyncHandlers>b__0(UICommandParameter`1 p)
   at Microsoft.Practices.Prism.Commands.DelegateCommand`1.<>c__DisplayClass1_0.<.ctor>b__0(Object o)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.<>c__DisplayClass4_0.<.ctor>b__0(Object arg)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.Execute(Object parameter)
   at Microsoft.Practices.Prism.Commands.DelegateCommand`1.Execute(T parameter)
   at Microsoft.PowerBI.Client.Windows.Commands.CompositeCommand`1.Execute(ICommand command, Object parameter)
   at Microsoft.Practices.Prism.Commands.CompositeCommand.Execute(Object parameter)
   at Microsoft.PowerBI.Client.Windows.Commands.CompositeCommand`1.Execute(T parameter)
   at Microsoft.PowerBI.Client.Windows.FileMenuHostService.Import(String id)
   at Microsoft.PowerBI.Client.Windows.FileMenuHostService.<>c__DisplayClass29_0.<HandleMenuItem>b__0()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<HandleAwaitableAsyncExceptions>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.HandleAwaitableAsyncExceptions(IExceptionHandler exceptionHandler, Func`1 asyncFunc)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<HandleAsyncExceptions>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.HandleAsyncExceptions(IExceptionHandler exceptionHandler, Func`1 asyncFunc)
   at Microsoft.PowerBI.Client.Windows.HostServiceDispatcher.<>c__DisplayClass8_0.<ExecuteOnUIThreadAsync>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.Mashup.Host.Document.SynchronizationContextExtensions.<>c__DisplayClass5_0.<Post>b__0(Object null)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.PowerBI.Client.Program.<>c.<Main>b__4_11()
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass4_0.<Main>b__1()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<>c__DisplayClass3_0.<HandleExceptionsWithNestedTasks>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.HandleExceptionsWithNestedTasks(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)

PowerBINonFatalError:
{"AppName":"PBIDesktop","AppVersion":"2.91.884.0","ModuleName":"","Component":"Microsoft.Mashup.Evaluator.ChannelMessenger","Error":"Microsoft.Mashup.Host.Document.SerializedException - System.NullReferenceException","MethodDef":"CreateChannel","ErrorOffset":""}

Snapshot Trace Logs:
C:\Users\xxxxxx\AppData\Local\Microsoft\Power BI Desktop\FrownSnapShota15b3ffa-2e84-4760-9963-575d47d46a40.zip

Model Default Mode:
Empty

Model Version:
PowerBI_V1

Performance Trace Logs:
C:\Users\xxxxxx\AppData\Local\Microsoft\Power BI Desktop\PerformanceTraces.zip

Enabled Preview Features:
PBI_JsonTableInference
PBI_NewWebTableInference
PBI_ImportTextByExample
PBI_ExcelTableInference
PBI_eimInformationProtectionForDesktop

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_SpanishLinguisticsEnabled
PBI_qnaLiveConnect
PBI_azureMapVisual
PBI_dataPointLassoSelect
PBI_compositeModelsOverAS
PBI_narrativeTextBox
PBI_dynamicParameters
PBI_anomalyDetection
PBI_newFieldList
PBI_cartesianMultiplesAuthoring

Disabled DirectQuery Options:
TreatHanaAsRelationalSource

Cloud:
GlobalCloud

PowerBINonFatalError_ErrorDescription:
System.NullReferenceException

PowerBIUserFeedbackServices_IsReported:
True

Formulas:

section Section1;
</details>

**Comment by manuelap-msft** [comment]
Hello,

this is an error we sometimes see when you're not on the latest version of Power BI Desktop. 
1. Can you please upgrade Power BI Desktop to the latest version?
2. Can you select "Cancel" there and see if a better error message is available from the "Refresh" screen (currently hidden behind the Something went wrong pop up) - sometimes when you scroll down there, there's one table causing issues with a better error message?
Thank you
Manuela

**Comment by manuelap-msft** [comment]
PS: If this is for the same tenant as  your other issue #548, then you're likely hitting limitations of the TDS endpoint in Power BI which can only return 80 MB.

You can learn more about how to connect to Dataverse from Power BI here, which documents the two different connectors and their limitations.
https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-powerbi-connector#connect-to-dataverse-using-the-connector

As we have had a few customers hit this issue, we have just published a new version of the CoE Starter kit reports - one using the new Dataverse connector (that's using the TDS endpoint) and one using the old Common Data Service (Legacy) connector that's using Import and can be used for datasets larger than 80MB.

You can download the new release here aka.ms/coestarterkitdownload and use the Legacy_CoEDashboard_202106.pbit to connect to your Dataverse instance. Please note that when using the Legacy_ dashboard, you have to enter the Environment URL with https:// at the beginning again.

We have added all these instructions to our documentation and are waiting for them to be published (hopefully later today or tomorrow). I will update this thread here once the instructions are live.

Thank you
Manuela

**Comment by mschaefer85** [comment]
Thank you for your quick reply.

We've installed a new version of Power BI Desktop, but the errors remain the same:

![image](https://user-images.githubusercontent.com/10259284/120447871-4a56b900-c38b-11eb-9ac2-bc6683b63d1f.png)
![image](https://user-images.githubusercontent.com/10259284/120447909-52165d80-c38b-11eb-8312-73d0557a6f80.png)
![image](https://user-images.githubusercontent.com/10259284/120447932-580c3e80-c38b-11eb-9226-35189a52d9dc.png)

But according to your last reply, we'll try to download the new release and try the Legacy_CoEDashboard_202106.pbit.

I'll keep you updated.

**Comment by manuelap-msft** [comment]
Typically, the "A connection was successfully established with the server, but then an error occurres during the pre-login handshake" happens when ports that the TDS endpoint requires are blocked. Here's a link to troubleshoot connection problems: https://docs.microsoft.com/en-us/powerapps/developer/data-platform/dataverse-sql-query#troubleshooting-connection-problems that you can try.

If not, the Legacy_ should work as it is not using the TDS endpoint.

Thank you
Manuela

**Comment by abhishekmaru** [comment]
Hi,

Thank you for the reply, As suggested performed the following steps:
1.  Upgraded Power BI Desktop to the latest version (2.93.981.0) from the following url: https://www.microsoft.com/en-us/download/details.aspx?id=58494

2. Download the new release here aka.ms/coestarterkitdownload and use the Legacy_CoEDashboard_202106.pbit.
 strangely getting the version error while importing Legacy_CoEDashboard_202106.pbit. Here are the screen shot:
<img width="403" alt="Error" src="https://user-images.githubusercontent.com/82568150/120456327-1d1e0100-c3b3-11eb-81d0-bccbeca5df3c.PNG">

**Comment by abhishekmaru** [comment]
Hello,

Still the same errors, here are screen shots:
<img width="376" alt="E1" src="https://user-images.githubusercontent.com/82568150/120466701-fd8bd600-c3bc-11eb-8f8a-94f04d100778.PNG">
<img width="373" alt="E2" src="https://user-images.githubusercontent.com/82568150/120466709-febd0300-c3bc-11eb-8e07-f3b91f2d7920.PNG">
<img width="381" alt="E3" src="https://user-images.githubusercontent.com/82568150/120466711-ff559980-c3bc-11eb-87ee-a64e0a10fd23.PNG">

**Comment by manuelap-msft** [comment]
Can you scroll down the "Refresh" screen and share all the error messages?

**Comment by abhishekmaru** [comment]
Following are the remaining error messages:

<img width="377" alt="E4" src="https://user-images.githubusercontent.com/82568150/120470719-8147c180-c3c1-11eb-8b3c-ea5287543ec6.PNG">
<img width="380" alt="E5" src="https://user-images.githubusercontent.com/82568150/120470727-8278ee80-c3c1-11eb-8991-4ca9a4ecf4a5.PNG">

**Comment by abhishekmaru** [comment]
Hi, any feedback on this issue.

**Comment by JeneferM-MSFT** [comment]
You will need to use the Legacy_CoEDashboard_202106.pbit instead due to your tenant size. 
Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) to retrieve
