### ISSUE TITLE
[CoE Starter Kit - BUG] Data Export not exporting environments from non US regions

### ISSUE THREAD

**Issue by Titoleto** [microsoft/coe-starter-kit#5713]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have found that the Data Export has only downloaded the streams from the environments in the USA region, but all those in the Europe region have not downloaded any.

Do we have to do anything to make it download the flows of the whole tenant? The problem is that the vast majority of environments and flows are in the European region, in the USA there are only 8 environments :(

I have navigated to the storage browser, and in the powerplatform>powerautomate>Flows folder, I onlye see 8 files

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Data Export Flows

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Unfortunately that is the product's Data Export feature, not our kit, and so we cannot help to mend the situation directly. 

Please contact product support and we will also let the product team know internally.

**Comment by Titoleto** [comment]
> Unfortunately that is the product's Data Export feature, not our kit, and so we cannot help to mend the situation directly.
> 
> Please contact product support and we will also let the product team know internally.
Thank you very much!

We will try to talk to a Microsoft engineer or else, use the version with the cloud flows because this way, we have thousands of unidentified flows.

Regards

**Comment by Jenefer-Monroe** [comment]
is this issue still impacting you?

**Comment by Titoleto** [comment]
> 

Yes, there is already a person from Microsoft reviewing the problem, the incident has been opened as a low type, so it may take some time to resolve it.

Thanks for your interest

**Comment by Titoleto** [comment]
> Unfortunately that is the product's Data Export feature, not our kit, and so we cannot help to mend the situation directly.
> 
> Please contact product support and we will also let the product team know internally.

Look at the reply they gave me after so many days of waiting

_**As you are facing issues with the CoE starter kit, I was informed that Microsoft Dynamics Support does not cover the support for this topic. Instead, you would need to reach out to the Developers of the product directly at GitHub**_

I suppose that as this functionality is in preview, they are not paying much attention to me, although I think it is something that should be reviewed as soon as possible.

Regards

**Comment by manuelap-msft** [comment]
Hello @Titoleto, apologies for not responding here sooner - can you please let me know the Microsoft Support Ticket number, so I can escalate this internally? You should have received better support via Microsoft Support, and as this is a product feature (even in preview) they should have forwarded this to our Engineering team. If you let me know the Support Ticket number, I'll work directly with Engineering so they can pick this up. Thank you!

**Comment by Titoleto** [comment]
Hello @manuelap-msft , just today they closed it, the ticket number was 2306070050000510.

Basically what they have told us is that as it is a product that is in preview, they are not giving support at the moment.

A week ago, all the flows of the European environments appeared, so something must have been fixed, but we could see that some flows were set in a different environment.

Thank you very much!

**Comment by manuelap-msft** [comment]
Thank you for providing the ticket number - I'll follow up internally here so that the support experience can be improved in the future.

Is your inventory now up to date again and you're receiving files for all environments, or is there still an issue?

**Comment by manuelap-msft** [comment]
Thanks for the update, that's good news at least!

Regarding the Legacy- environment, that's a known limitation we have documented here
https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq-dataexport#known-limitations

The Default- and Legacy- environments share the same GUID, and as the CoE kit uses GUID (unique IDs) to associate apps/flows to an environment, it can't currently handle the scenario for these very old legacy environments. Unfortunately that's a limitation in the CoE kit.

**Comment by Titoleto** [comment]
> Thanks for the update, that's good news at least!
> 
> Regarding the Legacy- environment, that's a known limitation we have documented here https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq-dataexport#known-limitations
> 
> The Default- and Legacy- environments share the same GUID, and as the CoE kit uses GUID (unique IDs) to associate apps/flows to an environment, it can't currently handle the scenario for these very old legacy environments. Unfortunately that's a limitation in the CoE kit.

Is it possible to eliminate the legacy environment?

**Comment by manuelap-msft** [comment]
I'm not sure. It looks like the Legacy- environment stems from a time when Power Apps was in Public Preview (around 2016) and was then left in favour of the Default- environment to support some data model / hosting changes that were made when Power Apps became GA. I could only find this very old blog post on the topic https://powerapps.microsoft.com/en-us/blog/migration-from-public-preview/ which says

> Microsoft PowerApps and Common Data Service have been released as Generally Available (GA). Many of you have been using the Common Data Service and PowerApps in Public Preview, however, even though you will be able to access your existing apps, flows, and Common Data Service databases in Preview, these resources will not be automatically upgraded to the new release due to compatibility issues. Instead we are sharing instructions on how to work with these resources, as well as how to manually migrate them to a GA environment.

If anything in your Legacy environment is still being used, you'd have to look at migrating that to a different environment and then I think you can delete the environment. But it's not something I have experience with, the tenants I have access to have been created after 2016 so don't have a Legacy- environment so it's not something we can test or investigate ourselves. I also couldn't find other documentation regarding the Legacy- environment anymore.

**Comment by manuelap-msft** [comment]
If this problem still exists, please raise a Microsoft Support ticket. Closing out as no action needed from CoE kit team.
