### ISSUE TITLE
[CoE Starter Kit - BUG] August Release Set App Permissions Application Getting User Photo Failure

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#6460]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/017aeb30-8cbc-4059-8038-aac4bbd1ec15)

It seems to still let you set the permissions however you still get this error.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Dont know

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, this appears to be some new setting for Admins as we've gotten a bunch of these over the last several weeks. We have added a new env variable which you can set which will allow you to not see these failures and just always see a sample image for them. See https://github.com/microsoft/coe-starter-kit/issues/6314, local fixed in Sept.

**Comment by Jenefer-Monroe** [comment]
Closing at as no further action for starter kit team

**Comment by mdphung** [comment]
@Jenefer-Monroe I am still seeing this  I went from August to November 
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/ebe1e8ff-9bb6-4f52-b6f1-69d2374ab5d2)

Also I have this variable set
