### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Set app quarantine status

### ISSUE THREAD

**Issue by vrmag** [microsoft/coe-starter-kit#9791]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

We installed April's CoE release yesterday to our CoE Sandbox environment and overnight a flow named Admin | Set app quarantine status ran and sent an email out for every app in the powerapps app table informing that the app has been released from quarantine. Initial investigation looks like the flow only sent out the emails to our Admin/service account not to any other owners.

We have checked our Prod flow and that did not run (Prod still on March CoE release). 

Can you please advise if this was meant to happen?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.26.2

### What app or flow are you having the issue with?

Admin | Set app quarantine status

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by D3L05** [comment]
Had the same issue, but in our case it sent the email to all the makers in our prod environments and also in our dev and sandbox environments which are excluded from compliance flows

![Image](https://github.com/user-attachments/assets/715128c6-a6f0-4bae-9dbe-e5e19aa3c779)

![Image](https://github.com/user-attachments/assets/9a8e085d-3067-4b68-8b67-cc325ba26df6)

**Comment by vynarim** [comment]
Hello, same issue for me this morning after installing the CoE yesterday
Email sent to every maker for every kind of environment
Any idea if it will be only done once or every days/week ?

**Comment by Service-WebDevPowerP** [comment]
Same issue as well, does anyone know where the Quarentined apps are listed?

**Comment by D3L05** [comment]
> Same issue as well, does anyone know where the Quarentined apps are listed?

You can see them in the Power Platform Admin View

**Comment by Service-WebDevPowerP** [comment]
is there any response from Microsoft on this issue?

**Comment by beefeeder** [comment]
We updated our CoE on the 30th, and since then the "Admin | Set app quarantine status" has been running 1.4k times per day. This was really curious considering it's only meant to run when the "admin_appisquarantined" column is modified.

Looking further into it, it appears there may be a mistake in the logic. The Quarantine or Release condition checks if admin_appisquarantined is equal to false, and if so it releases the app. 

This should be checking if it's equal to true, I'd imagine, as if it's not quarantined there's nothing to release, but the table is being updated due to the clear quarantine date action.

<img width="1218" alt="Image" src="https://github.com/user-attachments/assets/efbba92e-ba7b-4fb0-90f9-fbe7aedd49ac" />

**Comment by RajeevPentyala** [comment]
@vrmag and @beefeeder We picked up this issue. We will troubleshoot it at our end and will provide an update.

**Comment by RajeevPentyala** [comment]
Fixed an issue with expression setting the **Quarantine App Date** value.

![Image](https://github.com/user-attachments/assets/48b88c62-c9b0-4e2c-961b-d2c241c86bad)

**Comment by vrmag** [comment]
Hi @RajeevPentyala will this be fixed in June's release or July's? Thank you

**Comment by clarkeks** [comment]
> Fixed an issue with expression setting the **Quarantine App Date** value.
> 
> ![Image](https://github.com/user-attachments/assets/48b88c62-c9b0-4e2c-961b-d2c241c86bad)

I don't believe this will resolve the issue. the issue stems from the fact that the Sync helper flow is modifying the quarantine state which triggers this flow, which only has two options, release or quarantine.

**Comment by PokkeDEV** [comment]
@clarkeks : I completely agree—the proposed change won’t address the root cause. 

Admin | Set app quarantine status --> Trigger: 

<img width="631" height="420" alt="Image" src="https://github.com/user-attachments/assets/2d8cfaa9-8982-4633-8e97-a24bf7cb1072" />


It seems to be the same issue as #9983.

**Comment by MariusDeffner** [comment]
If we update to latest version, will the mail send again, or is this only one time?
Do not want to annoy our makers again

**Comment by Miguel102** [comment]
Has anyone found a working workaround to at least stop sending the e-mails in cases that weren't supposed to? Just updated our CoE, multiple makers got the huge flow of emails on the first night after, and now I think it's being triggered every night for apps that were developed on the previous day.

**Comment by beefeeder** [comment]
> Has anyone found a working workaround to at least stop sending the e-mails in cases that weren't supposed to? Just updated our CoE, multiple makers got the huge flow of emails on the first night after, and now I think it's being triggered every night for apps that were developed on the previous day.

I just turned our quarantine flows off for now, unfortunately. I'm not sure it's related to the date. I think it's running the unquarantine action on apps that are not quarantined, and this is updating the admin_appisquarantined column which triggers the flow again. I don't see any other reason why we'd be getting emails sent out for apps that are not quarantined

**Comment by AmarSaiRam** [comment]
Dear User, 

We noticed that this issue has been pending for quite some time, and we have not received any recent updates from your end. In the absence of further communication, we are proceeding to close this ticket, assuming that your concerns have been addressed or resolved. 
If you continue to experience any difficulties related to this matter, please feel free to open a new support ticket. This will help us ensure prompt and effective assistance, rather than reopening the new Issue. 
Thank you for your understanding and cooperation. 

Best Regards, 
CoE Starter Kit Team

**Comment by crowdedLeopard** [comment]
@AmarSaiRam @RajeevPentyala  did this actually get fixed ? ....contributors are suggesting it still isnt working
